server:
  port: 8006

spring:
  application:
    name: consul-payment-provider
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: consul-1
      port: 8500
