server:
  port: 5001

spring:
  application:
    name: storage-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: storage${server.port}
    prefer-ip-address: true # 能够显示真实id