server:
  port: 80

spring:
  application:
    name: consul-order-consumer

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}